export const services = [
  {
    id: "1",
    title: "Organizare Funerară",
    description:
      "Oferim suport complet în organizarea ceremoniei funerare, gestionând fiecare detaliu cu grijă și respect.",
    includes: [
      "Consiliere și suport familial 24/7",
      "Pregătirea și aranjarea defunctului",
      "Coordonarea ceremoniei religioase",
      "Aranjamente florale",
      "Gestionarea documentelor necesare",
    ],
    icon: "ceremony",
    image:
      "https://images.unsplash.com/photo-1644666218912-5c4069dc05f0?w=800&q=80",
    imageAlt: "Ceremonie funerară",
  },
  {
    id: "2",
    title: "Transport Funerar",
    description:
      "Servicii de transport funerar cu vehicule specializate, asigurând demnitate și discreție pe tot parcursul.",
    includes: [
      "Transport local și național",
      "Vehicule funerare moderne",
      "Echipă profesionistă și respectuoasă",
      "Disponibilitate 24/7",
      "Repatriere internațională",
    ],
    icon: "transport",
    image:
      "https://images.unsplash.com/photo-1644413803439-730e71d289db?w=800&q=80",
    imageAlt: "Vehicul funerar",
  },
  {
    id: "3",
    title: "Monumente și Cruci",
    description:
      "Confecționăm și montăm monumente funerare din granit și marmură, personalizate conform dorințelor familiei.",
    includes: [
      "Monumente din granit și marmură",
      "Gravuri și inscripții personalizate",
      "Instalare profesionistă",
      "Cruci și plăci comemorative",
      "Garanție la lucrările executate",
    ],
    icon: "monument",
    image:
      "https://images.unsplash.com/photo-1572547030508-9c9c9d2140bf?w=800&q=80",
    imageAlt: "Cruce monument funerar din granit",
  },
  {
    id: "4",
    title: "Asistență Acte",
    description:
      "Vă sprijinim în obținerea tuturor documentelor necesare, reducând birocrația într-un moment dificil.",
    includes: [
      "Certificat de deces",
      "Acte necesare înhumării",
      "Legalizare documente",
      "Comunicare cu autoritățile",
      "Consiliere juridică de bază",
    ],
    icon: "documents",
    image:
      "https://plus.unsplash.com/premium_photo-1664476694468-3c15e62d1710?w=800&q=80",
    imageAlt: "Asistenţă acte oficiale",
  },
];

export const categories = [
  {
    name: "Monumente Standart",
    description: "Granit clasic, design simplu și durabil",
    image: "https://images.unsplash.com/photo-1572547030508-9c9c9d2140bf?w=600&q=80",
  },
  {
    name: "Monumente Duble",
    description: "Pentru cupluri sau familii, design unitar",
    image: "https://images.unsplash.com/photo-1719870173939-e6638ab2ff0a?w=600&q=80",
  },
  {
    name: "Monumente Vip",
    description: "Marmură și granit premium, execuție exclusivă",
    image: "https://images.unsplash.com/photo-1699901610376-8f9fc9dea24b?w=600&q=80",
  },
  {
    name: "Monumente Copii",
    description: "Modele delicate, realizate cu maximă grijă",
    image: "https://images.unsplash.com/photo-1715707584649-978be309f5d0?w=600&q=80",
  },
  {
    name: "Monumente Complex",
    description: "Ansambluri complete cu toate accesoriile",
    image: "https://plus.unsplash.com/premium_photo-1681760626332-dde763f43d5b?w=600&q=80",
  },
  {
    name: "Monumente Gri",
    description: "Granit gri natural, aspect sobru și elegant",
    image: "https://images.unsplash.com/photo-1580557815329-e6612d802a52?w=600&q=80",
  },
  {
    name: "Monumente Beton Armat",
    description: "Rezistente și accesibile, finisaj îngrijit",
    image: "https://images.unsplash.com/photo-1639857831139-02a1f7be0449?w=600&q=80",
  },
  {
    name: "Accesorii Monumente",
    description: "Lanterne, vaze, ghivece și plăcuțe",
    image: "https://images.unsplash.com/photo-1763702246634-e895301c1767?w=600&q=80",
  },
  {
    name: "Garduri Morminte",
    description: "Borduri și garduri din granit sau metal",
    image: "https://images.unsplash.com/photo-1762037634162-226ba42d503d?w=600&q=80",
  },
  {
    name: "Mese si Scaune",
    description: "Seturi din granit pentru odihna la mormânt",
    image: "https://images.unsplash.com/photo-1595062584313-47018e0ee5cb?w=600&q=80",
  },
  {
    name: "Scari si Pervazuri",
    description: "Din granit sau marmură, șlefuite și polisate",
    image: "https://images.unsplash.com/photo-1771573391561-ab2bfc7e27a7?w=600&q=80",
  },
  {
    name: "Cruci",
    description: "Cruci din granit cu gravuri ornamentale",
    image: "https://images.unsplash.com/photo-1724602964173-6cc017be527e?w=600&q=80",
  },
  {
    name: "Sicrie",
    description: "Sicrie din lemn masiv, diferite modele",
    image: "https://images.unsplash.com/photo-1644666218912-5c4069dc05f0?w=600&q=80",
  },
  {
    name: "Coroane",
    description: "Coroane funerare naturale și artificiale",
    image: "https://images.unsplash.com/photo-1486102515046-44130769cb25?w=600&q=80",
  },
  {
    name: "Fundatii din Granit",
    description: "Fundații solide din granit pentru mormânt",
    image: "https://images.unsplash.com/photo-1620402507006-e7a8933006fe?w=600&q=80",
  },
  {
    name: "Fundatii din Beton Armat",
    description: "Fundații durabile din beton armat",
    image: "https://plus.unsplash.com/premium_photo-1723708933720-3e2ce7ad75ba?w=600&q=80",
  },
];

export const products = [
  // ── Monumente Standart ───────────────────────────────────────
  {
    id: "ms1",
    name: "Monument Granit Negru Standard",
    category: "Monumente Standart",
    material: "Granit negru",
    price: 3200,
    originalPrice: 3800,
    image: "https://images.unsplash.com/photo-1572547030508-9c9c9d2140bf?w=800&q=80",
    description: "Monument funerar din granit negru standard, șlefuit și polisat, cu gravură personalizată inclusă. Design clasic, rezistent la intemperii.",
    featured: true,
  },
  {
    id: "ms2",
    name: "Monument Granit Import",
    category: "Monumente Standart",
    material: "Granit import",
    price: 2800,
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1580557815329-e6612d802a52?w=800&q=80",
    description: "Monument din granit de import, finisaj superior, dimensiuni standard. Include inscripție personalizată și montaj profesionist.",
    featured: false,
  },

  // ── Monumente Duble ──────────────────────────────────────────
  {
    id: "md1",
    name: "Monument Dublu Granit Negru",
    category: "Monumente Duble",
    material: "Granit negru",
    price: 6500,
    originalPrice: 7200,
    image: "https://images.unsplash.com/photo-1719870173939-e6638ab2ff0a?w=800&q=80",
    description: "Monument dublu familial din granit negru, cu spațiu pentru două inscripții personalizate. Design unitar, montaj complet garantat.",
    featured: false,
  },
  {
    id: "md2",
    name: "Monument Dublu Granit Impala",
    category: "Monumente Duble",
    material: "Granit Impala gri",
    price: 5500,
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1639857831139-02a1f7be0449?w=800&q=80",
    description: "Monument dublu din granit Impala gri, suprafețe polisate și flamate, ideal pentru cupluri. Include gravuri decorative personalizate.",
    featured: false,
  },

  // ── Monumente Vip ────────────────────────────────────────────
  {
    id: "mv1",
    name: "Monument Marmură cu Statuetă",
    category: "Monumente Vip",
    material: "Marmură albă italiană",
    price: 14000,
    originalPrice: 16000,
    image: "https://images.unsplash.com/photo-1699901610376-8f9fc9dea24b?w=800&q=80",
    description: "Monument de excepție din marmură albă italiană, cu statuetă sculptată manual, gravuri fine și soclu din granit. Lucrare unică, realizată la comandă.",
    featured: true,
  },
  {
    id: "mv2",
    name: "Monument VIP Granit Negru Premium",
    category: "Monumente Vip",
    material: "Granit negru premium",
    price: 11000,
    originalPrice: null,
    image: "https://plus.unsplash.com/premium_photo-1681760626332-dde763f43d5b?w=800&q=80",
    description: "Monument VIP din granit negru de calitate superioară, fotografie porțelan inclusă, ornamente fine și montaj garantat.",
    featured: false,
  },

  // ── Monumente Copii ──────────────────────────────────────────
  {
    id: "mc1",
    name: "Monument Copii cu Înger",
    category: "Monumente Copii",
    material: "Marmură albă",
    price: 2800,
    originalPrice: 3200,
    image: "https://images.unsplash.com/photo-1715707584649-978be309f5d0?w=800&q=80",
    description: "Monument funerar pentru copii cu înger sculptat din marmură albă. Realizat cu delicatețe și respect, include inscripție personalizată.",
    featured: false,
  },
  {
    id: "mc2",
    name: "Monument Copii Cruce Granit",
    category: "Monumente Copii",
    material: "Granit roz",
    price: 1900,
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1724602964173-6cc017be527e?w=800&q=80",
    description: "Cruce funerară pentru copii din granit roz, design delicat cu ornamente florale gravate. Include soclu și montaj complet.",
    featured: false,
  },

  // ── Monumente Complex ────────────────────────────────────────
  {
    id: "mcx1",
    name: "Ansamblu Funerar Complet",
    category: "Monumente Complex",
    material: "Granit + Marmură",
    price: 15000,
    originalPrice: 18000,
    image: "https://plus.unsplash.com/premium_photo-1681760626332-dde763f43d5b?w=800&q=80",
    description: "Ansamblu funerar de lux: monument principal, cruce, borduri, plăcuțe laterale, fotografie, vaze și lanterne incluse. Realizat integral la comandă.",
    featured: false,
  },
  {
    id: "mcx2",
    name: "Monument Complex cu Borduri",
    category: "Monumente Complex",
    material: "Granit negru",
    price: 9500,
    originalPrice: 11000,
    image: "https://images.unsplash.com/photo-1699901610376-8f9fc9dea24b?w=800&q=80",
    description: "Ansamblu monument + borduri complete + cruce + accesorii. Pachet complet pentru o amenajare demnă și durabilă.",
    featured: false,
  },

  // ── Monumente Gri ────────────────────────────────────────────
  {
    id: "mgr1",
    name: "Monument Granit Gri Polisat",
    category: "Monumente Gri",
    material: "Granit gri",
    price: 2500,
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1580557815329-e6612d802a52?w=800&q=80",
    description: "Monument funerar din granit gri natural, șlefuit și polisat. Design clasic, accesibil, cu rezistență îndelungată la intemperii.",
    featured: false,
  },
  {
    id: "mgr2",
    name: "Monument Granit Gri cu Gravuri",
    category: "Monumente Gri",
    material: "Granit gri import",
    price: 3200,
    originalPrice: 3600,
    image: "https://images.unsplash.com/photo-1572547030508-9c9c9d2140bf?w=800&q=80",
    description: "Monument din granit gri de import cu gravuri ornamentale și fotografie porțelan inclusă. Finisaj mixt: polisat și flamat.",
    featured: false,
  },

  // ── Monumente Beton Armat ────────────────────────────────────
  {
    id: "mb1",
    name: "Monument Beton Armat Simplu",
    category: "Monumente Beton Armat",
    material: "Beton armat",
    price: 1800,
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1639857831139-02a1f7be0449?w=800&q=80",
    description: "Monument funerar din beton armat, rezistent și accesibil. Finisaj tencuit, potrivit pentru orice tip de mormânt. Include inscripție.",
    featured: false,
  },
  {
    id: "mb2",
    name: "Monument Beton cu Placare Granit",
    category: "Monumente Beton Armat",
    material: "Beton armat + Granit",
    price: 2400,
    originalPrice: 2800,
    image: "https://images.unsplash.com/photo-1572547030508-9c9c9d2140bf?w=800&q=80",
    description: "Monument din beton armat placat cu granit negru. Combinație economică și estetică, durabilitate sporită față de variantele clasice.",
    featured: false,
  },

  // ── Accesorii Monumente ──────────────────────────────────────
  {
    id: "am1",
    name: "Lanternă Funerară Inox",
    category: "Accesorii Monumente",
    material: "Inox 316L",
    price: 350,
    originalPrice: 420,
    image: "https://images.unsplash.com/photo-1763702246634-e895301c1767?w=800&q=80",
    description: "Lanternă funerară din inox de calitate superioară, rezistentă la coroziune și intemperii. Design elegant, potrivită pentru orice mormânt.",
    featured: false,
  },
  {
    id: "am2",
    name: "Vază Granit pentru Flori",
    category: "Accesorii Monumente",
    material: "Granit negru",
    price: 450,
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1595062584313-47018e0ee5cb?w=800&q=80",
    description: "Vază pentru flori din granit negru polisat. Fixare în soclu inclusă, potrivită pentru buchete naturale sau artificiale.",
    featured: false,
  },
  {
    id: "am3",
    name: "Plăcuță Comemorativă Gravată",
    category: "Accesorii Monumente",
    material: "Granit negru",
    price: 600,
    originalPrice: 750,
    image: "https://images.unsplash.com/photo-1620402507006-e7a8933006fe?w=800&q=80",
    description: "Plăcuță comemorativă gravată cu laser din granit negru. Text și fotografie personalizate. Montaj simplu pe orice suprafață.",
    featured: false,
  },

  // ── Garduri Morminte ─────────────────────────────────────────
  {
    id: "gm1",
    name: "Gard Mormânt Granit Negru",
    category: "Garduri Morminte",
    material: "Granit negru",
    price: 3500,
    originalPrice: 4000,
    image: "https://images.unsplash.com/photo-1762037634162-226ba42d503d?w=800&q=80",
    description: "Gard de mormânt din granit negru, set complet cu colțare și borduri. Dimensiuni standard, rezistente la îngheț. Montaj inclus.",
    featured: false,
  },
  {
    id: "gm2",
    name: "Bordură Granit Gri (set 4 piese)",
    category: "Garduri Morminte",
    material: "Granit gri",
    price: 1200,
    originalPrice: 1500,
    image: "https://images.unsplash.com/photo-1580557815329-e6612d802a52?w=800&q=80",
    description: "Set de 4 bucăți bordură din granit gri pentru delimitarea mormântului. Dimensiuni standard, ușor de montat, rezistente la îngheț.",
    featured: false,
  },

  // ── Mese si Scaune ───────────────────────────────────────────
  {
    id: "mss1",
    name: "Masă Funerară din Granit",
    category: "Mese si Scaune",
    material: "Granit negru",
    price: 2200,
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1595062584313-47018e0ee5cb?w=800&q=80",
    description: "Masă funerară din granit negru, șlefuită și polisată. Dimensiuni standard, rezistentă la toate condițiile meteorologice.",
    featured: false,
  },
  {
    id: "mss2",
    name: "Set Masă și Scaune din Granit",
    category: "Mese si Scaune",
    material: "Granit gri",
    price: 3800,
    originalPrice: 4500,
    image: "https://images.unsplash.com/photo-1771573391561-ab2bfc7e27a7?w=800&q=80",
    description: "Set complet masă + 2 scaune din granit gri. Design funcțional și elegant, perfect pentru vizitele la cimitir. Montaj inclus.",
    featured: false,
  },

  // ── Scari si Pervazuri ───────────────────────────────────────
  {
    id: "sp1",
    name: "Scări din Granit (3 trepte)",
    category: "Scari si Pervazuri",
    material: "Granit negru",
    price: 1800,
    originalPrice: 2100,
    image: "https://images.unsplash.com/photo-1771573391561-ab2bfc7e27a7?w=800&q=80",
    description: "Set 3 trepte din granit negru, șlefuite antiderapant. Dimensiuni standard, potrivite pentru acces la morminte sau capele.",
    featured: false,
  },
  {
    id: "sp2",
    name: "Pervaz Fereastră din Granit",
    category: "Scari si Pervazuri",
    material: "Granit gri",
    price: 650,
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1620402507006-e7a8933006fe?w=800&q=80",
    description: "Pervaz de fereastră sau ușă din granit gri natural. La comandă, dimensiuni personalizate. Rezistent și ușor de întreținut.",
    featured: false,
  },

  // ── Cruci ────────────────────────────────────────────────────
  {
    id: "cr1",
    name: "Cruce Granit cu Gravuri Ornamentale",
    category: "Cruci",
    material: "Granit Impala",
    price: 3200,
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1724602964173-6cc017be527e?w=800&q=80",
    description: "Cruce funerară din granit Impala gri, cu gravuri ornamentale și inscripție personalizată. Suprafețe mixte: polisate și flamate.",
    featured: true,
  },
  {
    id: "cr2",
    name: "Cruce Granit Simplă",
    category: "Cruci",
    material: "Granit gri",
    price: 1200,
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1715707584649-978be309f5d0?w=800&q=80",
    description: "Cruce funerară din granit gri, solidă și durabilă. Suprafețe șlefuite, potrivită pentru orice tip de mormânt. Inscripție inclusă.",
    featured: false,
  },

  // ── Sicrie ───────────────────────────────────────────────────
  {
    id: "si1",
    name: "Sicriu Lemn Masiv Brad",
    category: "Sicrie",
    material: "Lemn brad masiv",
    price: 1800,
    originalPrice: 2200,
    image: "https://images.unsplash.com/photo-1644666218912-5c4069dc05f0?w=800&q=80",
    description: "Sicriu din lemn masiv de brad, finisat cu lac mat. Model clasic cu mânere inox. Disponibil în mai multe dimensiuni.",
    featured: false,
  },
  {
    id: "si2",
    name: "Sicriu Premium Stejar",
    category: "Sicrie",
    material: "Lemn stejar masiv",
    price: 3500,
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1644413803439-730e71d289db?w=800&q=80",
    description: "Sicriu din lemn masiv de stejar, finisat premium. Mânere sculptate, căptușeală de catifea. Model elegant și demn.",
    featured: false,
  },

  // ── Coroane ──────────────────────────────────────────────────
  {
    id: "co1",
    name: "Coroană Funerară Naturală Mare",
    category: "Coroane",
    material: "Flori naturale",
    price: 350,
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1486102515046-44130769cb25?w=800&q=80",
    description: "Coroană funerară mare din flori naturale, aranjament personalizabil. Livrare la domiciliu sau la locul ceremoniei.",
    featured: false,
  },
  {
    id: "co2",
    name: "Coroană Artificială Premium",
    category: "Coroane",
    material: "Flori artificiale premium",
    price: 220,
    originalPrice: 280,
    image: "https://images.unsplash.com/photo-1595062584313-47018e0ee5cb?w=800&q=80",
    description: "Coroană funerară din flori artificiale de calitate superioară, rezistentă la intemperii. Aspect natural, durabilitate maximă.",
    featured: false,
  },

  // ── Fundatii din Granit ──────────────────────────────────────
  {
    id: "fg1",
    name: "Fundație Mormânt Granit Negru",
    category: "Fundatii din Granit",
    material: "Granit negru",
    price: 2800,
    originalPrice: 3200,
    image: "https://images.unsplash.com/photo-1620402507006-e7a8933006fe?w=800&q=80",
    description: "Fundație completă pentru mormânt din granit negru, cu toate elementele necesare. Include montaj profesionist și nivelarea terenului.",
    featured: false,
  },
  {
    id: "fg2",
    name: "Fundație Granit cu Borduri Incluse",
    category: "Fundatii din Granit",
    material: "Granit gri",
    price: 3500,
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1771573391561-ab2bfc7e27a7?w=800&q=80",
    description: "Fundație din granit gri cu borduri integrate. Set complet pentru delimitarea și pavarea mormântului. Garanție la lucrare.",
    featured: false,
  },

  // ── Fundatii din Beton Armat ─────────────────────────────────
  {
    id: "fb1",
    name: "Fundație Beton Armat Standard",
    category: "Fundatii din Beton Armat",
    material: "Beton armat",
    price: 1200,
    originalPrice: null,
    image: "https://plus.unsplash.com/premium_photo-1723708933720-3e2ce7ad75ba?w=800&q=80",
    description: "Fundație standard pentru mormânt din beton armat. Rezistentă, accesibilă, cu montaj inclus. Timp de execuție 1-2 zile.",
    featured: false,
  },
  {
    id: "fb2",
    name: "Fundație Beton cu Placare Granit",
    category: "Fundatii din Beton Armat",
    material: "Beton armat + Granit",
    price: 1800,
    originalPrice: 2100,
    image: "https://images.unsplash.com/photo-1639857831139-02a1f7be0449?w=800&q=80",
    description: "Fundație din beton armat cu placare din granit natural. Combinație economică cu aspect premium. Montaj inclus, garanție 5 ani.",
    featured: false,
  },
];

export const companyInfo = {
  name: "PrimNord Granit",
  phone: "079 175 383",
  description:
    "Cu peste 15 ani de experiență, PrimNord Granit oferă servicii funerare complete cu respect, grijă și profesionalism. Suntem alături de familii în cele mai dificile momente.",
};
